import type { Snapshot, VenueFloor } from "./types";

export const XIANG_FLOOR: VenueFloor = {
  width: 240,
  height: 420,
  gate: { x: 120, y: 18, label: "场口" },
  plots: [
    { id: "p01", no: "01", x: 10, y: 28, w: 68, h: 36, use: "snack" },
    { id: "p02", no: "02", x: 18, y: 70, w: 52, h: 28, use: "snack" },
    { id: "p03", no: "03", x: 18, y: 104, w: 52, h: 28, use: "snack" },
    { id: "p08", no: "08", x: 18, y: 138, w: 52, h: 28, use: "snack" },
    { id: "p16", no: "16", x: 14, y: 172, w: 60, h: 32, use: "snack" },
    { id: "p20", no: "20", x: 8, y: 210, w: 72, h: 42, use: "fruit" },
    { id: "p07", no: "07", x: 22, y: 258, w: 40, h: 24, use: "service" },
    { id: "p09", no: "09", x: 18, y: 288, w: 52, h: 28, use: "snack" },
    { id: "p11", no: "11", x: 18, y: 322, w: 52, h: 28, use: "snack" },
    { id: "p22", no: "22", x: 14, y: 356, w: 60, h: 32, use: "snack" },
    { id: "p05", no: "05", x: 160, y: 28, w: 70, h: 40, use: "grill" },
    { id: "p06", no: "06", x: 168, y: 74, w: 52, h: 28, use: "snack" },
    { id: "p12", no: "12", x: 162, y: 108, w: 64, h: 32, use: "snack" },
    { id: "p13", no: "13", x: 168, y: 146, w: 52, h: 28, use: "snack" },
    { id: "p18", no: "18", x: 162, y: 180, w: 64, h: 32, use: "snack" },
    { id: "p14", no: "14", x: 168, y: 218, w: 52, h: 28, use: "snack" },
    { id: "p15", no: "15", x: 160, y: 252, w: 70, h: 40, use: "grill" },
    { id: "p17", no: "17", x: 168, y: 298, w: 52, h: 28, use: "snack" },
    { id: "p19", no: "19", x: 154, y: 332, w: 76, h: 40, use: "fruit" },
    { id: "p21", no: "21", x: 168, y: 378, w: 52, h: 24, use: "snack" },
  ],
};

/**
 * Six trading days already on the books, so the organizer's reconciliation page
 * has something to answer with the first time it is opened. 甜甜糖葫芦 stands the
 * venue up twice on purpose — that is the case the page exists for.
 */
const HISTORY: { stallId: string; name: string; plotNo: string; pattern: string }[] = [
  { stallId: "s-1", name: "王姐烤面筋", plotNo: "01", pattern: "aaaaaa" },
  { stallId: "s-2", name: "阿刘土家饼", plotNo: "", pattern: "wwaaww" },
  { stallId: "s-3", name: "陈记水果", plotNo: "20", pattern: "aa-aaa" },
  { stallId: "s-lin", name: "林晚烤冷面", plotNo: "18", pattern: "aaaa-a" },
  { stallId: "s-5", name: "马记烤串", plotNo: "05", pattern: "aaaaaa" },
  { stallId: "s-6", name: "甜甜糖葫芦", plotNo: "08", pattern: "anaana" },
  { stallId: "s-7", name: "福记煎饼", plotNo: "12", pattern: "aaaaaa" },
  { stallId: "s-8", name: "阿珍烤红薯", plotNo: "16", pattern: "aaanaa" },
];

const DAYS = ["2026-08-31", "2026-09-01", "2026-09-02", "2026-09-03", "2026-09-04", "2026-09-05"];

const DAY_LOG = DAYS.flatMap((date, i) =>
  HISTORY.map(({ stallId, name, plotNo, pattern }) => {
    // a = 出摊, n = 占了位没来, w = 报了没抢到, - = 那天没报名
    const mark = pattern[i];
    return {
      id: `${date}:${stallId}`,
      date,
      venueId: "venue-xiang",
      stallId,
      vendorName: name,
      signedUp: mark !== "-",
      allotted: mark === "a" || mark === "n",
      arrived: mark === "a",
      noShow: mark === "n",
      plotNo: mark === "a" || mark === "n" ? plotNo : "",
      plotsThatDay: XIANG_FLOOR.plots.length,
      salesYuan: mark === "a" ? 180 + ((i * 37 + stallId.length * 13) % 140) : 0,
      saleCount: mark === "a" ? 16 + ((i * 5 + stallId.length) % 12) : 0,
    };
  }).filter((row) => row.signedUp),
);

const FEE_PAID_AT = Date.parse("2026-09-02T02:00:00Z");

export const SEED: Snapshot = {
  vendorId: "v-lin",
  vendorName: "林晚烤冷面",
  organizerId: "o-site",
  organizerName: "巷口经营点管理员",
  venues: [
    {
      id: "venue-xiang",
      name: "巷口经营点",
      organizerId: "o-site",
      organizerName: "巷口经营点管理员",
      district: "本地",
      address: "原马路摊疏导后的固定场地",
      open: "17:00",
      close: "22:00",
      signupBy: "15:00",
      signupOpen: true,
      slots: XIANG_FLOOR.plots.length,
      floor: XIANG_FLOOR,
      feeYuanPerMonth: 800,
      note: "每天开门。每天 15:00 前报名今日摊位，不报当天不保证有位。管理费线下收。",
      closedToday: false,
      cover: "/stalls/venue.jpg",
    },
  ],
  stalls: [
    {
      id: "s-1",
      venueId: "venue-xiang",
      vendorId: "v-wang",
      vendorName: "王姐烤面筋",
      category: "小吃",
      fromStreet: "原地铁口流动摊",
      phone: "13800010001",
      appliedAt: Date.parse("2026-08-21T02:00:00Z"),
      cover: "/stalls/wang.jpg",
      blurb: "铁板滋滋响，面筋现烤现撕。",
      status: "active",
      compliant: true,
      licenseTier: "ordering",
      orderingRequested: false,
      orderingPaused: false,
      feePaidThisMonth: true,
      feePaidAt: FEE_PAID_AT,
      signedUpToday: true,
      allottedToday: true,
      arrivedToday: true,
      packedUpToday: false,
      noShowToday: false,
      signedUpAt: 1,
      lotSlot: 1,
      lotPlotId: "p01",
      plotPreference: "only",
      lastPlotId: "p01",
    },
    {
      id: "s-2",
      venueId: "venue-xiang",
      vendorId: "v-liu",
      vendorName: "阿刘土家饼",
      category: "小吃",
      fromStreet: "原学校门口流动摊",
      phone: "13800020002",
      appliedAt: Date.parse("2026-08-22T02:00:00Z"),
      cover: "/stalls/liu.jpg",
      blurb: "酱香土家饼，现烙出锅。",
      status: "active",
      compliant: true,
      licenseTier: "display",
      orderingRequested: false,
      orderingPaused: false,
      feePaidThisMonth: false,
      feePaidAt: 0,
      signedUpToday: false,
      allottedToday: false,
      arrivedToday: false,
      packedUpToday: false,
      noShowToday: false,
      signedUpAt: 0,
      lotSlot: 0,
      lotPlotId: "",
      plotPreference: "only",
      lastPlotId: "",
    },
    {
      id: "s-3",
      venueId: "venue-xiang",
      vendorId: "v-chen",
      vendorName: "陈记水果",
      category: "水果",
      fromStreet: "原小区门口流动摊",
      phone: "13800030003",
      appliedAt: Date.parse("2026-08-23T02:00:00Z"),
      cover: "/stalls/chen.jpg",
      blurb: "当晚切开，论份装盒。",
      status: "active",
      compliant: true,
      licenseTier: "display",
      orderingRequested: false,
      orderingPaused: false,
      feePaidThisMonth: true,
      feePaidAt: FEE_PAID_AT,
      signedUpToday: true,
      allottedToday: true,
      arrivedToday: false,
      packedUpToday: false,
      noShowToday: false,
      signedUpAt: 2,
      lotSlot: 20,
      lotPlotId: "p20",
      plotPreference: "only",
      lastPlotId: "p20",
    },
    {
      id: "s-lin",
      venueId: "venue-xiang",
      vendorId: "v-lin",
      vendorName: "林晚烤冷面",
      category: "小吃",
      fromStreet: "原商场西侧人行道",
      phone: "13800040004",
      appliedAt: Date.parse("2026-08-24T02:00:00Z"),
      cover: "/stalls/lin.jpg",
      blurb: "冷面过热板，边焦里软。",
      status: "active",
      compliant: true,
      licenseTier: "display",
      orderingRequested: false,
      orderingPaused: false,
      feePaidThisMonth: false,
      feePaidAt: 0,
      signedUpToday: false,
      allottedToday: false,
      arrivedToday: false,
      packedUpToday: false,
      noShowToday: false,
      signedUpAt: 0,
      lotSlot: 18,
      lotPlotId: "p18",
      plotPreference: "only",
      lastPlotId: "p18",
    },
    {
      id: "s-4",
      venueId: "venue-xiang",
      vendorId: "v-zhou",
      vendorName: "周师傅修伞",
      category: "便民",
      fromStreet: "原街角无证摊",
      phone: "13800050005",
      appliedAt: Date.parse("2026-08-25T02:00:00Z"),
      cover: "/stalls/wang.jpg",
      blurb: "修伞补伞，当场取。",
      status: "pending",
      compliant: false,
      licenseTier: "display",
      orderingRequested: false,
      orderingPaused: false,
      feePaidThisMonth: false,
      feePaidAt: 0,
      signedUpToday: false,
      allottedToday: false,
      arrivedToday: false,
      packedUpToday: false,
      noShowToday: false,
      signedUpAt: 0,
      lotSlot: 0,
      lotPlotId: "",
      plotPreference: "only",
      lastPlotId: "",
    },
    {
      id: "s-5",
      venueId: "venue-xiang",
      vendorId: "v-ma",
      vendorName: "马记烤串",
      category: "烤串",
      fromStreet: "原夜市西口流动摊",
      phone: "13800060006",
      appliedAt: Date.parse("2026-08-26T02:00:00Z"),
      cover: "/stalls/ma.jpg",
      blurb: "炭火现烤，孜然要得开。",
      status: "active",
      compliant: true,
      licenseTier: "display",
      orderingRequested: false,
      orderingPaused: false,
      feePaidThisMonth: true,
      feePaidAt: FEE_PAID_AT,
      signedUpToday: true,
      allottedToday: true,
      arrivedToday: true,
      packedUpToday: false,
      noShowToday: false,
      signedUpAt: 10,
      lotSlot: 5,
      lotPlotId: "p05",
      plotPreference: "only",
      lastPlotId: "p05",
    },
    {
      id: "s-6",
      venueId: "venue-xiang",
      vendorId: "v-tian",
      vendorName: "甜甜糖葫芦",
      category: "小吃",
      fromStreet: "原公园门口流动摊",
      phone: "13800070007",
      appliedAt: Date.parse("2026-08-27T02:00:00Z"),
      cover: "/stalls/tian.jpg",
      blurb: "山楂现蘸，脆糖壳。",
      status: "active",
      compliant: true,
      licenseTier: "display",
      orderingRequested: false,
      orderingPaused: false,
      feePaidThisMonth: false,
      feePaidAt: 0,
      signedUpToday: true,
      allottedToday: true,
      arrivedToday: false,
      packedUpToday: false,
      noShowToday: false,
      signedUpAt: 11,
      lotSlot: 8,
      lotPlotId: "p08",
      plotPreference: "only",
      lastPlotId: "p08",
    },
    {
      id: "s-7",
      venueId: "venue-xiang",
      vendorId: "v-fu",
      vendorName: "福记煎饼",
      category: "小吃",
      fromStreet: "原公交站流动摊",
      phone: "13800080008",
      appliedAt: Date.parse("2026-08-28T02:00:00Z"),
      cover: "/stalls/fu.jpg",
      blurb: "摊饼摊蛋，现摊现卷。",
      status: "active",
      compliant: true,
      licenseTier: "ordering",
      orderingRequested: false,
      orderingPaused: false,
      feePaidThisMonth: true,
      feePaidAt: FEE_PAID_AT,
      signedUpToday: true,
      allottedToday: true,
      arrivedToday: true,
      packedUpToday: false,
      noShowToday: false,
      signedUpAt: 12,
      lotSlot: 12,
      lotPlotId: "p12",
      plotPreference: "only",
      lastPlotId: "p12",
    },
    {
      id: "s-8",
      venueId: "venue-xiang",
      vendorId: "v-zhen",
      vendorName: "阿珍烤红薯",
      category: "小吃",
      fromStreet: "原巷口铁桶摊",
      phone: "13800090009",
      appliedAt: Date.parse("2026-08-20T02:00:00Z"),
      cover: "/stalls/zhen.jpg",
      blurb: "炉里焖软，掰开冒热气。",
      status: "active",
      compliant: true,
      licenseTier: "display",
      orderingRequested: false,
      orderingPaused: false,
      feePaidThisMonth: true,
      feePaidAt: FEE_PAID_AT,
      signedUpToday: true,
      allottedToday: true,
      arrivedToday: false,
      packedUpToday: false,
      noShowToday: false,
      signedUpAt: 13,
      lotSlot: 16,
      lotPlotId: "p16",
      plotPreference: "only",
      lastPlotId: "p16",
    },
  ],
  dishes: [
    { id: "d-1", stallId: "s-1", name: "烤面筋", priceYuan: 8, onTonight: true, photo: "/dishes/mianjin.jpg" },
    { id: "d-2", stallId: "s-1", name: "辣味烤面筋", priceYuan: 10, onTonight: true, photo: "/dishes/mianjin-spicy.jpg" },
    { id: "d-3", stallId: "s-3", name: "当季水果一份", priceYuan: 12, onTonight: true, photo: "/dishes/fruit.jpg" },
    { id: "d-4", stallId: "s-lin", name: "烤冷面", priceYuan: 12, onTonight: true, photo: "/dishes/lengmian.jpg" },
    { id: "d-5", stallId: "s-lin", name: "加煎蛋", priceYuan: 3, onTonight: true, photo: "/dishes/egg.jpg" },
    { id: "d-10", stallId: "s-5", name: "羊肉串", priceYuan: 8, onTonight: true, photo: "/dishes/chuan.jpg" },
    { id: "d-11", stallId: "s-5", name: "烤茄子", priceYuan: 6, onTonight: true, photo: "/dishes/chuan.jpg" },
    { id: "d-12", stallId: "s-6", name: "山楂糖葫芦", priceYuan: 5, onTonight: true, photo: "/dishes/tanghulu.jpg" },
    { id: "d-13", stallId: "s-6", name: "草莓糖葫芦", priceYuan: 8, onTonight: true, photo: "/dishes/tanghulu.jpg" },
    { id: "d-14", stallId: "s-7", name: "煎饼果子", priceYuan: 10, onTonight: true, photo: "/dishes/jianbing.jpg" },
    { id: "d-15", stallId: "s-7", name: "加火腿", priceYuan: 3, onTonight: true, photo: "/dishes/egg.jpg" },
    { id: "d-16", stallId: "s-8", name: "蜜汁烤红薯", priceYuan: 6, onTonight: true, photo: "/dishes/hongshu.jpg" },
    { id: "d-17", stallId: "s-8", name: "原味烤红薯", priceYuan: 5, onTonight: true, photo: "/dishes/hongshu.jpg" },
  ],
  consumerId: "c-me",
  consumerName: "路过的人",
  demoMinutes: 14 * 60,
  tradingDate: "2026-09-06",
  dayStartedAt: Date.parse("2026-09-05T16:00:00Z"),
  dayLog: DAY_LOG,
  sales: [],
  orders: [],
  disputes: [],
  reviews: [
    { id: "r-1", stallId: "s-1", stars: 5, note: "面筋烤得刚好，辣的也干净。", nick: "路过的人", at: 1 },
    { id: "r-2", stallId: "s-lin", stars: 4, note: "冷面边焦，取餐号好找。", nick: "今晚来吃", at: 2 },
    { id: "r-3", stallId: "s-5", stars: 5, note: "串香，炭火味足。到摊付也快。", nick: "附近住的", at: 3 },
    { id: "r-4", stallId: "s-7", stars: 4, note: "煎饼热，小程序下单不用排队点。", nick: "上班路过", at: 4 },
    { id: "r-5", stallId: "s-8", stars: 5, note: "红薯软，掰开烫手。", nick: "带小孩来的", at: 5 },
  ],
};
